from PyRouge.pyrouge import Rouge
r = Rouge()
system_generated_summary = "I just say Jenn the director of effortless English.I have something exciting to talk about today.What a strange word!Well, what I'm doing is I'm doing small little podcast on Twitter, and I am doing these almost everyday, because it's so easy.I use my phone my iPhone and I record a short talk about some Topic in my daily life, my normal life, and then I put it on Twitter twitter.com, and this is a very easy way for you to get more easy.English listening about daily topics about normal daily life, so I am continuing the podcast, of course, but the podcast is usually about learning ideas, teaching ideas.How can you speak English better?Just now I did a short audio, tweet and audio little podcast, just two and a half minutes about the weather in San Francisco.So if you want to hear new English listening topics everyday, please follow me on Twitter, so you will get longer more serious listening here at the podcast and you can get almost daily listening about easy, simple topics on my Twitter page.Com, A J Hoge that / a j, a h, o g e twitter.com forward, slash AJ Hoge!There'S a button that says follow click the follow button.Since I can use my phone, my cell phone, when I'm walking around the city when I'm doing my normal life, sometimes I will stop and talk for one or two minutes about something happening in my life and put it on my Twitter page.So you can get a lot of new, easy, daily life English listening this way it's twitter.com flash AJ Hoge."

manual_summmary = "I just say Jenn the director of effortless English.I am now doing audio tweets. I use my phone my iPhone and I record a short talk about some Topic in my daily life, my normal life, and then I put it on Twitter twitter.com, and this is a very easy way for you to get more easy.English listening about daily topics about normal daily life, so I am continuing the podcast, of course, but the podcast is usually about learning ideas, teaching ideas. How can you speak English better?It'S about very simple day today: topics, for example. Just now I did a short audio, tweet and audio little podcast, just two and a half minutes about the weather in San Francisco.So how can you follow me on Twitter?You can make a Twitter account and then follow me. There'S a button that says follow click the follow button.So you can get a lot of new, easy, daily life English listening this way it's twitter.com flash AJ Hoge."

print (r.rouge_l([system_generated_summary], [manual_summmary]))
[precision, recall, f_score] = r.rouge_l([system_generated_summary], [manual_summmary])

